### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by CharlyP** [lee-dohm/tabs-to-spaces#19]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v0.8.1

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/src/config.js:0

TypeError: undefined is not a function
  at ScopeDescriptor.module.exports.ScopeDescriptor.getScopeChain (/usr/share/atom/resources/app/src/scope-descriptor.js:29:26)
  at Config.module.exports.Config.getRawScopedValue (/usr/share/atom/resources/app/src/config.js:730:72)
  at Config.module.exports.Config.get (/usr/share/atom/resources/app/src/config.js:163:22)
  at /home/charles/.atom/packages/tabs-to-spaces/lib/index.coffee:36:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:961:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:596:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app/src/workspace-element.js:287:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by lee-dohm** [comment]
Please update to the latest version of Atom, currently v0.176.0. I've also updated v0.8.1 to only install on post-API-freeze versions of Atom ... which I suspect is what the problem was here. After you've updated, please let me know if you can reproduce the issue.

Thanks for reporting it!
