### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by taybson** [lee-dohm/tabs-to-spaces#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v0.8.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/workspace.js:614

TypeError: undefined is not a function
  at ScopeDescriptor.module.exports.ScopeDescriptor.getScopeChain (/Applications/Atom.app/Contents/Resources/app/src/scope-descriptor.js:29:26)
  at Config.module.exports.Config.getRawScopedValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:733:72)
  at Config.module.exports.Config.get (/Applications/Atom.app/Contents/Resources/app/src/config.js:164:22)
  at /Users/Steven/.atom/packages/tabs-to-spaces/lib/index.coffee:36:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:961:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
  3x -7:27.9 core:backspace (input.hidden-input)
     -7:17.3 core:confirm (input.hidden-input)
     -0:12.0 tabs-to-spaces:untabify (input.hidden-input)
     -0:08.9 core:select-all (input.hidden-input)
     -0:02.9 tabs-to-spaces:untabify (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment]
Please update to the latest version of Atom, currently v0.179.0, and let me know if this error reoccurs.

**Comment by lee-dohm** [comment]
This is most likely because the initial release of v0.8.1 was put out with an incorrect Atom engine specification. Please update to the latest version of Atom and let me know if this reproduces.

Thanks for reporting!

**Comment by taybson** [comment]
Hi Lee,

Sorry for late reply,

I did update the atom to the latest version. 

It stops complaining the errors.

Thank you for your kindly help.

Steven.
