### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by orenard** [lee-dohm/tabs-to-spaces#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: linux 3.13.0-66-generic
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v0.11.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/src/workspace.js:614

TypeError: undefined is not a function
  at ScopeDescriptor.module.exports.ScopeDescriptor.getScopeChain (/usr/share/atom/resources/app/src/scope-descriptor.js:29:26)
  at Config.module.exports.Config.getRawScopedValue (/usr/share/atom/resources/app/src/config.js:733:72)
  at Config.module.exports.Config.get (/usr/share/atom/resources/app/src/config.js:164:22)
  at /home/orenard/.atom/packages/tabs-to-spaces/lib/index.coffee:44:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:961:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/usr/share/atom/resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)

```

### Commands

```
     -1:18.8 core:move-right (input.hidden-input)
     -1:18.5 core:save (input.hidden-input)
     -0:42.1 command-palette:toggle (input.hidden-input)
     -0:36.7 settings-view:install-packages (input.hidden-input)
     -0:33.4 core:confirm (input.hidden-input)
     -0:19.9 core:select-all (input.hidden-input)
     -0:19.4 core:save (input.hidden-input)
     -0:10.4 core:select-all (input.hidden-input)
     -0:05.6 core:move-right (input.hidden-input)
     -0:05.2 core:move-left (input.hidden-input)
 13x -0:04.8 core:move-right (input.hidden-input)
  2x -0:02.0 core:delete (input.hidden-input)
     -0:00.4 snippets:next-tab-stop (input.hidden-input)
     -0:00.4 snippets:expand (input.hidden-input)
     -0:00.4 editor:indent (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
cssbeautify, v1.1.2
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment]
I'm not even sure how you were able to install the current version of tabs-to-spaces on v0.165.0 of Atom, since tabs-to-spaces v0.11.1 requires at least v0.201.0 to function as stated in the `package.json`. Please update to the current version of Atom and let me know if the error reoccurs.
