### ISSUE TITLE
Uncaught TypeError: TabsToSpaces is not a function

### ISSUE THREAD

**Issue by curator** [lee-dohm/tabs-to-spaces#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v1.0.0

### Stack Trace

Uncaught TypeError: TabsToSpaces is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

TypeError: TabsToSpaces is not a function
    at Object.module.exports.loadModule (/Users/pnorvell/.atom/packages/tabs-to-spaces/lib/index.coffee:1:1)
    at /Users/pnorvell/.atom/packages/tabs-to-spaces/lib/index.coffee:45:14
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1010:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "move-panes"
    ]
  },
  "tabs-to-spaces": {
    "onSave": "untabify"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-beautify, v0.28.19
go-plus, v3.5.2
language-docker, v1.1.3
language-groovy, v0.4.0
language-hcl, v0.1.2
language-powershell, v2.1.0
language-puppet, v0.15.0
line-ending-converter, v1.3.2
linter, v1.11.2
linter-puppet-lint, v0.6.1
minimap, v4.16.1
pretty-json, v0.4.1
project-manager, v2.6.5
tabs-to-spaces, v1.0.0

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Thanks for reporting. I'll take a look at it as soon as I get home from work in a couple hours.

**Comment by lee-dohm** [comment]
I'm pretty sure that this is only an issue when upgrading from inside the application. I've got an idea to fix it though.

**Comment by guilhermecarvalhocarneiro** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.2
**System**: Unknown Windows Version
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v1.0.1


### Stack Trace

Uncaught TypeError: TabsToSpaces is not a function

```
At /C:/Users/guilh/.atom/packages/tabs-to-spaces/lib/index.coffee:71

TypeError: TabsToSpaces is not a function
    at Object.module.exports.loadModule (file:///C:/Users/guilh/.atom/packages/tabs-to-spaces/lib/index.coffee:1:1)
    at atom-workspace.commands.atom.commands.add.tabs-to-spaces:tabify (file:///C:/Users/guilh/.atom/packages/tabs-to-spaces/lib/index.coffee:14:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\guilh\AppData\Local\atom\app-1.2.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\guilh\AppData\Local\atom\app-1.2.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\guilh\AppData\Local\atom\app-1.2.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\guilh\AppData\Local\atom\app-1.2.2\resources\app.asar\src\atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  2x -4:45.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:43.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:43.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:43.9.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -4:34.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:32 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:32 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:27.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -4:26.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:25.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:24 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:24 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:20.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:04.3.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:02.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.0 tabs-to-spaces:tabify (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "tabs-to-spaces": {
    "onSave": "untabify"
  }
}
```

### Installed Packages

```coffee
# User
aligner-python, v1.0.1
autocomplete-python, v0.10.4
color-picker, v2.0.13
minimap, v4.16.1
pigments, v0.19.0
python-tools, v0.6.6
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```
