### ISSUE TITLE
cant save files in last version

### ISSUE THREAD

**Issue by urielCurielMtz** [lee-dohm/tabs-to-spaces#59]
after update the package cant save my files and get this errot in atom inspector but dont display anyting
`Uncaught (in promise) TypeError: buffer.groupLastChanges is not a function
    at /home/opit/.atom/packages/tabs-to-spaces/lib/tabs-to-spaces.js:131:16
    at /home/opit/.atom/packages/tabs-to-spaces/lib/tabs-to-spaces.js:141:9
    at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TabsToSpaces.processBufferByLine (/home/opit/.atom/packages/tabs-to-spaces/lib/tabs-to-spaces.js:137:12)
    at TabsToSpaces.replaceWhitespaceWithTabs (/home/opit/.atom/packages/tabs-to-spaces/lib/tabs-to-spaces.js:120:10)
    at TabsToSpaces.tabify (/home/opit/.atom/packages/tabs-to-spaces/lib/tabs-to-spaces.js:22:10)
    at /home/opit/.atom/packages/tabs-to-spaces/lib/index.js:47:20
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.<anonymous> (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:157:18)
    at /opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1288:38`

**Comment by lee-dohm** [comment]
Thanks for the report!

Which version of Atom are you running?

**Comment by urielCurielMtz** [comment]
@lee-dohm this is my atom version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by lee-dohm** [comment]
Can you update to the latest version at https://atom.io? The currently released version is v1.25.1.

**Comment by urielCurielMtz** [comment]
I already updated atom and it was corrected but now I got errors from other packages hehe
